embeddings {
  tensor_name: "grid_id:06500"
  metadata_path: "06500/grid_id\\metadata.tsv"
  tensor_path: "06500/grid_id\\tensors.tsv"
}
embeddings {
  tensor_name: "hour:06500"
  metadata_path: "06500/hour\\metadata.tsv"
  tensor_path: "06500/hour\\tensors.tsv"
}
embeddings {
  tensor_name: "day_of_week:06500"
  metadata_path: "06500/day_of_week\\metadata.tsv"
  tensor_path: "06500/day_of_week\\tensors.tsv"
}
embeddings {
  tensor_name: "month:06500"
  metadata_path: "06500/month\\metadata.tsv"
  tensor_path: "06500/month\\tensors.tsv"
}
embeddings {
  tensor_name: "is_weekend:06500"
  metadata_path: "06500/is_weekend\\metadata.tsv"
  tensor_path: "06500/is_weekend\\tensors.tsv"
}
embeddings {
  tensor_name: "grid_id:06760"
  metadata_path: "06760/grid_id\\metadata.tsv"
  tensor_path: "06760/grid_id\\tensors.tsv"
}
embeddings {
  tensor_name: "hour:06760"
  metadata_path: "06760/hour\\metadata.tsv"
  tensor_path: "06760/hour\\tensors.tsv"
}
embeddings {
  tensor_name: "day_of_week:06760"
  metadata_path: "06760/day_of_week\\metadata.tsv"
  tensor_path: "06760/day_of_week\\tensors.tsv"
}
embeddings {
  tensor_name: "month:06760"
  metadata_path: "06760/month\\metadata.tsv"
  tensor_path: "06760/month\\tensors.tsv"
}
embeddings {
  tensor_name: "is_weekend:06760"
  metadata_path: "06760/is_weekend\\metadata.tsv"
  tensor_path: "06760/is_weekend\\tensors.tsv"
}
